DOSKEY alias=npp "%~dp0\%0"
DOSKEY cat=type $*
DOSKEY cd=cd /D $* ^&^& "%~dp0\scripts\cmd-update-title.cmd"
DOSKEY clear=cls
DOSKEY cp=copy $*
DOSKEY dir=dir /A $*
DOSKEY e.=explorer .
DOSKEY git-acp=git add -A ^&^& git commit -m $* ^&^& git push origin
DOSKEY git-log=git log --oneline --all --graph --decorate  $*
DOSKEY grep=findstr $*
DOSKEY ls=dir /B
DOSKEY mcd=mkdir $* ^&^& cd $*
DOSKEY mv=move $*
DOSKEY pwd=echo %%cd%%
DOSKEY rimraf=rmdir /s /q $*
DOSKEY rm=del $*
REM DOSKEY touch=copy NUL /y $*
DOSKEY which=where $*

